const NOT_FOUND_CODE = 404;
const BAD_REQUEST_CODE = 400;
const SERVER_ERROR_CODE = 500;
const OK_CODE = 200;
const UNAUTHORIZED = 401;
const SALT = 10;

module.exports = {
  NOT_FOUND_CODE, BAD_REQUEST_CODE, SERVER_ERROR_CODE, OK_CODE, SALT, UNAUTHORIZED,
};
